title: Feature Idea
labels: ["enhancement", "discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for a new feature? We'd love to hear it!
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe your feature idea
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: What problem does this solve or what use case does it enable?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: If you have ideas on how to implement this, share them here
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?
