title: General Discussion
labels: ["discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for starting a discussion! We'd love to hear your thoughts.
  - type: textarea
    id: topic
    attributes:
      label: Discussion Topic
      description: What would you like to discuss?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant background or context
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other relevant information
